import type { Metadata } from 'next';
import { cookies } from 'next/headers';

import './globals.css';

import { Inter, Fira_Code } from 'next/font/google';
import { ToggleTheme } from '@/components/ToggleTheme';
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const firaCode = Fira_Code({ subsets: ['latin'], variable: '--font-fira-code' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = cookies().get('theme');
  const themeValue = theme?.value ?? 'light';

  return (
    <html lang='jp' className={themeValue}>
      <body className={`${firaCode.variable} ${inter.variable} container m-auto dark:bg-gray-800 dark:text-white`}>
        <div className='absolute top-1 right-1'>
          <ToggleTheme theme={themeValue} />
        </div>
        {children}
      </body>
    </html>
  );
}
