import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App | Blog',
  description: 'Generated by create next app',
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return (
    <main>
      <header>header</header>
      <div>{children}</div>
      <footer>footer</footer>
    </main>
  );
}
